import jsPDF from "jspdf";

export const generateExecutiveReport = ({
  sales,
  inventory,
  vendors,
  products,
  businessScore,
  businessStatus,
  managementPriority,
  managementMessage,
}) => {
  const pdf = new jsPDF("p", "mm", "a4");

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  const margin = 18;
  const contentWidth = pageWidth - margin * 2;

  let y = 20;

  // =========================================================
  // DATA
  // =========================================================

  const revenue = Number(sales?.total_revenue || 0);
  const orders = Number(sales?.total_orders || 0);
  const productsSold = Number(sales?.products_sold || 0);
  const averageOrderValue = Number(
    sales?.average_order_value || 0
  );

  const totalInventoryProducts = Number(
    inventory?.total_products || 0
  );

  const lowStock = Number(
    inventory?.low_stock_products || 0
  );

  const outOfStock = Number(
    inventory?.out_of_stock_products || 0
  );

  const topVendor =
    vendors?.length > 0 ? vendors[0] : null;

  const topProducts =
    products?.slice(0, 5) || [];

  const generatedDate = new Date().toLocaleDateString(
    "en-IN",
    {
      day: "numeric",
      month: "long",
      year: "numeric",
    }
  );

  // =========================================================
  // HELPERS
  // =========================================================

  const formatMoney = (value) => {
    return `Rs. ${Number(value || 0).toLocaleString(
      "en-IN",
      {
        maximumFractionDigits: 2,
      }
    )}`;
  };

  const addFooter = () => {
    const currentPage =
      pdf.internal.getNumberOfPages();

    pdf.setDrawColor(226, 232, 240);

    pdf.line(
      margin,
      pageHeight - 15,
      pageWidth - margin,
      pageHeight - 15
    );

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(8);
    pdf.setTextColor(100, 116, 139);

    pdf.text(
      "Generated by ShopSense Executive BI",
      margin,
      pageHeight - 9
    );

    pdf.text(
      `Page ${currentPage}`,
      pageWidth - margin,
      pageHeight - 9,
      {
        align: "right",
      }
    );
  };

  const checkPageBreak = (requiredSpace = 25) => {
    if (y + requiredSpace > pageHeight - 22) {
      addFooter();

      pdf.addPage();

      y = 20;
    }
  };

  const addSectionTitle = (title) => {
    checkPageBreak(22);

    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(16);
    pdf.setTextColor(15, 23, 42);

    pdf.text(title, margin, y);

    y += 5;

    pdf.setDrawColor(226, 232, 240);

    pdf.line(
      margin,
      y,
      pageWidth - margin,
      y
    );

    y += 10;
  };

  const addParagraph = (text) => {
    if (!text) return;

    const lines = pdf.splitTextToSize(
      String(text),
      contentWidth
    );

    checkPageBreak(lines.length * 5.5 + 8);

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(10);
    pdf.setTextColor(71, 85, 105);

    pdf.text(lines, margin, y);

    y += lines.length * 5.5 + 7;
  };

  const drawMetricCard = (
    x,
    yPosition,
    width,
    height,
    title,
    value
  ) => {
    pdf.setFillColor(248, 250, 252);
    pdf.setDrawColor(226, 232, 240);

    pdf.roundedRect(
      x,
      yPosition,
      width,
      height,
      4,
      4,
      "FD"
    );

    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(8);
    pdf.setTextColor(100, 116, 139);

    pdf.text(
      title.toUpperCase(),
      x + 5,
      yPosition + 7
    );

    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(13);
    pdf.setTextColor(15, 23, 42);

    pdf.text(
      String(value),
      x + 5,
      yPosition + 17
    );
  };

  const addBullet = (text, color = [79, 70, 229]) => {
    const lines = pdf.splitTextToSize(
      String(text),
      contentWidth - 12
    );

    checkPageBreak(lines.length * 5.5 + 7);

    pdf.setFillColor(...color);

    pdf.circle(
      margin + 2,
      y - 1.5,
      1.3,
      "F"
    );

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(10);
    pdf.setTextColor(71, 85, 105);

    pdf.text(
      lines,
      margin + 7,
      y
    );

    y += lines.length * 5.5 + 5;
  };

  // =========================================================
  // HEADER
  // =========================================================

  pdf.setFillColor(15, 23, 42);

  pdf.rect(
    0,
    0,
    pageWidth,
    55,
    "F"
  );

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(28);
  pdf.setTextColor(255, 255, 255);

  pdf.text(
    "ShopSense",
    margin,
    19
  );

  pdf.setFontSize(18);

  pdf.text(
    "Executive Business Report",
    margin,
    31
  );

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(10);
  pdf.setTextColor(203, 213, 225);

  pdf.text(
    "Marketplace Performance • Business Intelligence • Executive Reporting",
    margin,
    42
  );

  pdf.setDrawColor(99, 102, 241);
  pdf.setLineWidth(1);

  pdf.line(
    margin,
    48,
    pageWidth - margin,
    48
  );

  y = 68;

  // =========================================================
  // REPORT INFORMATION
  // =========================================================

  pdf.setFillColor(248, 250, 252);

  pdf.roundedRect(
    margin,
    y,
    contentWidth,
    25,
    4,
    4,
    "F"
  );

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(8);
  pdf.setTextColor(100, 116, 139);

  pdf.text(
    "REPORT TYPE",
    margin + 6,
    y + 8
  );

  pdf.text(
    "GENERATED",
    pageWidth / 2,
    y + 8
  );

  pdf.setFontSize(10);
  pdf.setTextColor(30, 41, 59);

  pdf.text(
    "Executive BI",
    margin + 6,
    y + 17
  );

  pdf.text(
    generatedDate,
    pageWidth / 2,
    y + 17
  );

  y += 38;

  // =========================================================
  // EXECUTIVE SUMMARY
  // =========================================================

  addSectionTitle("Executive Summary");

  const executiveSummary =
    `ShopSense generated ${formatMoney(
      revenue
    )} in marketplace revenue across ${orders.toLocaleString(
      "en-IN"
    )} orders. The marketplace recorded ${productsSold.toLocaleString(
      "en-IN"
    )} products sold with an average order value of ${formatMoney(
      averageOrderValue
    )}.`;

  addParagraph(executiveSummary);

  // =========================================================
  // KPI SNAPSHOT
  // =========================================================

  addSectionTitle("Performance Snapshot");

  const cardWidth = 40;
  const cardHeight = 27;
  const gap = 4.5;

  drawMetricCard(
    margin,
    y,
    cardWidth,
    cardHeight,
    "Revenue",
    formatMoney(revenue)
  );

  drawMetricCard(
    margin + cardWidth + gap,
    y,
    cardWidth,
    cardHeight,
    "Orders",
    orders.toLocaleString("en-IN")
  );

  drawMetricCard(
    margin + (cardWidth + gap) * 2,
    y,
    cardWidth,
    cardHeight,
    "Products Sold",
    productsSold.toLocaleString("en-IN")
  );

  drawMetricCard(
    margin + (cardWidth + gap) * 3,
    y,
    cardWidth,
    cardHeight,
    "Avg Order Value",
    formatMoney(averageOrderValue)
  );

  y += 38;

  // =========================================================
  // BUSINESS HEALTH
  // =========================================================

  addSectionTitle("Business Health");

  const healthColor =
    businessScore >= 80
      ? [22, 163, 74]
      : businessScore >= 60
      ? [245, 158, 11]
      : [220, 38, 38];

  pdf.setFillColor(248, 250, 252);
  pdf.setDrawColor(226, 232, 240);

  pdf.roundedRect(
    margin,
    y,
    contentWidth,
    42,
    4,
    4,
    "FD"
  );

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(10);
  pdf.setTextColor(71, 85, 105);

  pdf.text(
    "OPERATIONAL HEALTH SCORE",
    margin + 8,
    y + 10
  );

  pdf.setFontSize(27);
  pdf.setTextColor(...healthColor);

  pdf.text(
    `${businessScore}/100`,
    margin + 8,
    y + 25
  );

  pdf.setFontSize(11);

  pdf.text(
    businessStatus,
    margin + 55,
    y + 24
  );

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(9);
  pdf.setTextColor(100, 116, 139);

  pdf.text(
    "Operational indicator based on current marketplace inventory conditions.",
    margin + 8,
    y + 34
  );

  y += 52;

  // =========================================================
  // INVENTORY RISK
  // =========================================================

  addSectionTitle("Inventory Risk Analysis");

  addBullet(
    `Total inventory records: ${totalInventoryProducts.toLocaleString(
      "en-IN"
    )}`,
    [79, 70, 229]
  );

  addBullet(
    `Low-stock products: ${lowStock.toLocaleString(
      "en-IN"
    )}`,
    [245, 158, 11]
  );

  addBullet(
    `Out-of-stock products: ${outOfStock.toLocaleString(
      "en-IN"
    )}`,
    [220, 38, 38]
  );

  // =========================================================
  // MANAGEMENT PRIORITY
  // =========================================================

  addSectionTitle("Management Priority");

  pdf.setFillColor(255, 251, 235);
  pdf.setDrawColor(253, 230, 138);

  pdf.roundedRect(
    margin,
    y,
    contentWidth,
    35,
    4,
    4,
    "FD"
  );

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(12);
  pdf.setTextColor(146, 64, 14);

  pdf.text(
    managementPriority || "Monitor Marketplace",
    margin + 8,
    y + 10
  );

  const priorityLines = pdf.splitTextToSize(
    managementMessage ||
      "Continue monitoring marketplace performance.",
    contentWidth - 16
  );

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(10);
  pdf.setTextColor(120, 53, 15);

  pdf.text(
    priorityLines,
    margin + 8,
    y + 19
  );

  y += Math.max(
    45,
    priorityLines.length * 5 + 28
  );

  // =========================================================
  // LEADING VENDOR
  // =========================================================

  addSectionTitle("Vendor Performance");

  if (topVendor) {
    pdf.setFillColor(239, 246, 255);
    pdf.setDrawColor(191, 219, 254);

    pdf.roundedRect(
      margin,
      y,
      contentWidth,
      35,
      4,
      4,
      "FD"
    );

    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(12);
    pdf.setTextColor(30, 64, 175);

    pdf.text(
      "Leading Vendor",
      margin + 8,
      y + 10
    );

    pdf.setFontSize(14);
    pdf.setTextColor(15, 23, 42);

    pdf.text(
      topVendor.vendor_name || "Unknown",
      margin + 8,
      y + 20
    );

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(9);
    pdf.setTextColor(71, 85, 105);

    pdf.text(
      `Revenue: ${formatMoney(
        topVendor.revenue
      )}   •   Orders: ${Number(
        topVendor.orders || 0
      ).toLocaleString("en-IN")}   •   Products Sold: ${Number(
        topVendor.products_sold || 0
      ).toLocaleString("en-IN")}`,
      margin + 8,
      y + 29
    );

    y += 45;
  } else {
    addParagraph(
      "Vendor performance information is currently unavailable."
    );
  }

  // =========================================================
  // TOP PRODUCTS
  // =========================================================

  addSectionTitle("Top Performing Products");

  if (topProducts.length === 0) {
    addParagraph(
      "No product performance data is currently available."
    );
  } else {
    topProducts.forEach((product, index) => {
      checkPageBreak(20);

      const productName =
        product.product_name ||
        `Product ${index + 1}`;

      const unitsSold = Number(
        product.units_sold || 0
      );

      const productRevenue = Number(
        product.revenue || 0
      );

      pdf.setFillColor(255, 255, 255);
      pdf.setDrawColor(226, 232, 240);

      pdf.roundedRect(
        margin,
        y,
        contentWidth,
        19,
        3,
        3,
        "FD"
      );

      pdf.setFillColor(79, 70, 229);

      pdf.circle(
        margin + 7,
        y + 9,
        3,
        "F"
      );

      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(8);
      pdf.setTextColor(255, 255, 255);

      pdf.text(
        String(index + 1),
        margin + 7,
        y + 10,
        {
          align: "center",
        }
      );

      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(10);
      pdf.setTextColor(30, 41, 59);

      pdf.text(
        productName,
        margin + 14,
        y + 8
      );

      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(8);
      pdf.setTextColor(100, 116, 139);

      pdf.text(
        `${unitsSold.toLocaleString(
          "en-IN"
        )} units sold`,
        margin + 14,
        y + 14
      );

      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(9);
      pdf.setTextColor(79, 70, 229);

      pdf.text(
        formatMoney(productRevenue),
        pageWidth - margin - 5,
        y + 10,
        {
          align: "right",
        }
      );

      y += 24;
    });
  }

  // =========================================================
  // EXECUTIVE INSIGHTS
  // =========================================================

  addSectionTitle("Executive Insights");

  if (topVendor) {
    addBullet(
      `${topVendor.vendor_name} is currently the leading vendor by marketplace revenue.`
    );
  }

  if (topProducts.length > 0) {
    addBullet(
      `${topProducts[0].product_name} is currently the highest-selling product by units sold.`
    );
  }

  if (outOfStock > 0) {
    addBullet(
      `${outOfStock} product(s) are currently out of stock and require inventory attention.`,
      [220, 38, 38]
    );
  }

  if (lowStock > 0) {
    addBullet(
      `${lowStock} product(s) are currently at low-stock levels and should be monitored.`,
      [245, 158, 11]
    );
  }

  if (
    outOfStock === 0 &&
    lowStock === 0
  ) {
    addBullet(
      "Current inventory levels do not indicate immediate stockout concerns.",
      [22, 163, 74]
    );
  }

  // =========================================================
  // FINAL EXECUTIVE SUMMARY
  // =========================================================

  checkPageBreak(55);

  pdf.setFillColor(15, 23, 42);

  pdf.roundedRect(
    margin,
    y,
    contentWidth,
    48,
    4,
    4,
    "F"
  );

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(14);
  pdf.setTextColor(255, 255, 255);

  pdf.text(
    "Executive Conclusion",
    margin + 8,
    y + 11
  );

  const conclusion =
    outOfStock > 0
      ? `The marketplace is generating ${formatMoney(
          revenue
        )} in revenue, but immediate management attention is recommended for inventory availability, particularly the ${outOfStock} out-of-stock product(s).`
      : lowStock > 0
      ? `The marketplace is generating ${formatMoney(
          revenue
        )} in revenue with a ${businessStatus.toLowerCase()} operational position. Inventory replenishment should be monitored for ${lowStock} low-stock product(s).`
      : `The marketplace is generating ${formatMoney(
          revenue
        )} in revenue with a ${businessStatus.toLowerCase()} operational position and no immediate inventory availability concerns.`;

  const conclusionLines =
    pdf.splitTextToSize(
      conclusion,
      contentWidth - 16
    );

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(10);
  pdf.setTextColor(226, 232, 240);

  pdf.text(
    conclusionLines,
    margin + 8,
    y + 22
  );

  // =========================================================
  // FOOTER
  // =========================================================

  addFooter();

  // =========================================================
  // SAVE
  // =========================================================

  const dateForFile = new Date()
    .toISOString()
    .slice(0, 10);

  pdf.save(
    `ShopSense_Executive_Report_${dateForFile}.pdf`
  );
};