import jsPDF from "jspdf";

export const generateBusinessReport = (analytics, ai) => {
  const pdf = new jsPDF("p", "mm", "a4");

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  const margin = 18;
  const contentWidth = pageWidth - margin * 2;

  let y = 20;

  // ==================================================
  // HELPERS
  // ==================================================

  const formatMoney = (value) => {
  const amount = Number(value || 0);

  return `₹${amount.toLocaleString("en-IN", {
    maximumFractionDigits: 2,
  })}`;
};

const formatShortMoney = (value) => {
  const amount = Number(value || 0);

  if (amount >= 10000000)
    return `₹${(amount / 10000000).toFixed(2)} Cr`;

  if (amount >= 100000)
    return `₹${(amount / 100000).toFixed(2)} L`;

  return formatMoney(amount);
};

  const checkPageBreak = (requiredSpace = 25) => {
    if (y + requiredSpace > pageHeight - 20) {
      addFooter();
      pdf.addPage();
      y = 20;
    }
  };

  const addFooter = () => {
    const currentPage =
      pdf.internal.getNumberOfPages();

    pdf.setDrawColor(220, 220, 220);

    pdf.line(
      margin,
      pageHeight - 15,
      pageWidth - margin,
      pageHeight - 15
    );

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(8);
    pdf.setTextColor(120, 120, 120);

    pdf.text(
      "Generated by ShopSense Analytics",
      margin,
      pageHeight - 9
    );

    pdf.text(
      `Page ${currentPage}`,
      pageWidth - margin,
      pageHeight - 9,
      {
        align: "right",
      }
    );
  };

  const addSectionTitle = (title) => {
    checkPageBreak(20);

    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(16);
    pdf.setTextColor(30, 41, 59);

    pdf.text(title, margin, y);

    y += 4;

    pdf.setDrawColor(226, 232, 240);

    pdf.line(
      margin,
      y,
      pageWidth - margin,
      y
    );

    y += 10;
  };

  const addParagraph = (text) => {
    if (!text) return;

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(10.5);
    pdf.setTextColor(71, 85, 105);

    const lines = pdf.splitTextToSize(
      String(text),
      contentWidth
    );

    checkPageBreak(lines.length * 6 + 5);

    pdf.text(lines, margin, y);

    y += lines.length * 5.5 + 5;
  };

  const addBullet = (text) => {
    if (!text) return;

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(10.5);
    pdf.setTextColor(71, 85, 105);

    const lines = pdf.splitTextToSize(
      String(text),
      contentWidth - 8
    );

    checkPageBreak(lines.length * 6 + 5);

    pdf.setFillColor(79, 70, 229);

    pdf.circle(
      margin + 2,
      y - 1.3,
      1.2,
      "F"
    );

    pdf.text(
      lines,
      margin + 7,
      y
    );

    y += lines.length * 5.5 + 4;
  };

  const addNumberedItem = (text, index) => {
    if (!text) return;

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(10.5);
    pdf.setTextColor(71, 85, 105);

    const lines = pdf.splitTextToSize(
      String(text),
      contentWidth - 12
    );

    checkPageBreak(lines.length * 6 + 6);

    pdf.setFillColor(22, 163, 74);

    pdf.circle(
      margin + 3,
      y - 1.5,
      3,
      "F"
    );

    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(8);
    pdf.setTextColor(255, 255, 255);

    pdf.text(
      String(index + 1),
      margin + 3,
      y - 0.5,
      {
        align: "center",
      }
    );

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(10.5);
    pdf.setTextColor(71, 85, 105);

    pdf.text(
      lines,
      margin + 10,
      y
    );

    y += lines.length * 5.5 + 5;
  };

  // ==================================================
  // NEW PROFESSIONAL KPI CARD
  // ==================================================

  const drawMetricCard = (
    x,
    yPos,
    width,
    height,
    title,
    value,
    color
  ) => {
    pdf.setFillColor(250, 250, 252);

    pdf.setDrawColor(226, 232, 240);

    pdf.roundedRect(
      x,
      yPos,
      width,
      height,
      4,
      4,
      "FD"
    );

    pdf.setFillColor(...color);

    pdf.roundedRect(
      x,
      yPos,
      width,
      8,
      4,
      4,
      "F"
    );

    pdf.setFont(
      "helvetica",
      "bold"
    );

    pdf.setFontSize(8);
    pdf.setTextColor(
      255,
      255,
      255
    );

    pdf.text(
      title.toUpperCase(),
      x + width / 2,
      yPos + 5.5,
      {
        align: "center",
      }
    );

    pdf.setFont(
      "helvetica",
      "bold"
    );

    pdf.setFontSize(14);
    pdf.setTextColor(
      30,
      41,
      59
    );

    pdf.text(
      String(value),
      x + width / 2,
      yPos + 18,
      {
        align: "center",
      }
    );
  };

  // ==================================================
  // PROFESSIONAL REPORT HEADER
  // ==================================================

  pdf.setFillColor(15, 23, 42);

  pdf.rect(
    0,
    0,
    pageWidth,
    55,
    "F"
  );

  pdf.setFont(
    "helvetica",
    "bold"
  );

  pdf.setFontSize(28);
  pdf.setTextColor(
    255,
    255,
    255
  );

  pdf.text(
    "ShopSense",
    margin,
    18
  );

  pdf.setFontSize(18);

  pdf.text(
    "Business Intelligence Report",
    margin,
    30
  );

  pdf.setFont(
    "helvetica",
    "normal"
  );

  pdf.setFontSize(10);

  pdf.setTextColor(
    203,
    213,
    225
  );

  pdf.text(
    "Marketplace Performance • Vendor Analytics • AI Business Intelligence",
    margin,
    41
  );

  pdf.setDrawColor(
    99,
    102,
    241
  );

  pdf.setLineWidth(1);

  pdf.line(
    margin,
    47,
    pageWidth - margin,
    47
  );

  y = 70;

  // ==================================================
  // REPORT INFORMATION
  // ==================================================

  const vendorName =
    localStorage.getItem("name") ||
    "Marketplace Vendor";

  const generatedDate =
    new Date().toLocaleDateString(
      "en-IN",
      {
        day: "numeric",
        month: "long",
        year: "numeric",
      }
    );

  pdf.setFillColor(
    248,
    250,
    252
  );

  pdf.roundedRect(
    margin,
    y,
    contentWidth,
    25,
    3,
    3,
    "F"
  );

  pdf.setFont(
    "helvetica",
    "bold"
  );

  pdf.setFontSize(9);
  pdf.setTextColor(
    100,
    116,
    139
  );

  pdf.text(
    "VENDOR",
    margin + 6,
    y + 8
  );

  pdf.text(
    "GENERATED",
    pageWidth / 2 + 5,
    y + 8
  );

  pdf.setFontSize(11);
  pdf.setTextColor(
    30,
    41,
    59
  );

  pdf.text(
    vendorName,
    margin + 6,
    y + 17
  );

  pdf.text(
    generatedDate,
    pageWidth / 2 + 5,
    y + 17
  );

  y += 38;

  // ==================================================
// MARKETPLACE BENCHMARK
// ==================================================

addSectionTitle("Marketplace Benchmark");

const benchmark = analytics?.benchmark;

if (benchmark) {

  const cardWidth = 39;
  const cardHeight = 24;
  const gap = 6;

  drawMetricCard(
    margin,
    y,
    cardWidth,
    cardHeight,
    "Rank",
    `#${benchmark.vendor_rank}`,
    [79, 70, 229]
  );

  drawMetricCard(
    margin + cardWidth + gap,
    y,
    cardWidth,
    cardHeight,
    "Percentile",
    `${benchmark.percentile}%`,
    [16, 185, 129]
  );

  drawMetricCard(
    margin + (cardWidth + gap) * 2,
    y,
    cardWidth,
    cardHeight,
    "Revenue",
    formatShortMoney(benchmark.vendor_revenue),
    [245, 158, 11]
  );

  drawMetricCard(
    margin + (cardWidth + gap) * 3,
    y,
    cardWidth,
    cardHeight,
    "Status",
    benchmark.status,
    [239, 68, 68]
  );

  y += 34;

  // ----------------------------------------
  // Revenue Comparison Box
  // ----------------------------------------

  pdf.setFillColor(248,250,252);

  pdf.setDrawColor(226,232,240);

  pdf.roundedRect(
    margin,
    y,
    contentWidth,
    32,
    4,
    4,
    "FD"
  );

  pdf.setFont(
    "helvetica",
    "bold"
  );

  pdf.setFontSize(11);

  pdf.setTextColor(
    30,
    41,
    59
  );

  pdf.text(
    "Revenue Comparison",
    margin + 6,
    y + 8
  );

  pdf.setFont(
    "helvetica",
    "normal"
  );

  pdf.setFontSize(10);

  pdf.setTextColor(
    71,
    85,
    105
  );

  pdf.text(
    `Your Revenue : ${formatMoney(
      benchmark.vendor_revenue
    )}`,
    margin + 6,
    y + 17
  );

  pdf.text(
    `Marketplace Average : ${formatMoney(
      benchmark.market_average_revenue
    )}`,
    margin + 6,
    y + 25
  );

  const diff =
    benchmark.vendor_revenue -
    benchmark.market_average_revenue;

  const text =
    diff >= 0
      ? `Performance is ${Math.abs(
          (
            diff /
            benchmark.market_average_revenue
          ) *
            100
        ).toFixed(1)}% above the marketplace average.`
      : `Performance is ${Math.abs(
          (
            diff /
            benchmark.market_average_revenue
          ) *
            100
        ).toFixed(1)}% below the marketplace average.`;

  pdf.setFont(
    "helvetica",
    "italic"
  );

  pdf.setTextColor(
    99,
    102,
    241
  );

pdf.setFont("helvetica", "italic");
pdf.setFontSize(9);
pdf.setTextColor(79, 70, 229);

pdf.text(
  text,
  margin + 6,
  y + 33
);

  y += 52;

} else {

  addParagraph(
    "Marketplace benchmark information is currently unavailable."
  );

}
  // ==================================================
// BUSINESS INSIGHTS
// ==================================================

addSectionTitle("Business Insights");

if (analytics?.ai_insights?.length) {

  analytics.ai_insights.forEach((insight) => {

    let title = "";
let description = "";

if (typeof insight === "string") {

  description = insight;

} else {

  title =
    insight.title ||
    "";

  description =
    insight.description ||
    insight.message ||
    insight.insight ||
    insight.text ||
    "";

}

    checkPageBreak(20);

    pdf.setFillColor(248,250,252);

    pdf.setDrawColor(226,232,240);

    pdf.roundedRect(
      margin,
      y,
      contentWidth,
      18,
      4,
      4,
      "FD"
    );

    pdf.setFillColor(
      79,
      70,
      229
    );

    pdf.circle(
      margin + 6,
      y + 8,
      2,
      "F"
    );

    pdf.setFont(
  "helvetica",
  "bold"
);

pdf.setFontSize(10);

pdf.setTextColor(
  30,
  41,
  59
);

pdf.text(
  title,
  margin + 12,
  y + 7
);

pdf.setFont(
  "helvetica",
  "normal"
);

pdf.setFontSize(9);

pdf.setTextColor(
  100,
  116,
  139
);

const lines = pdf.splitTextToSize(
  description,
  contentWidth - 18
);

pdf.text(
  lines,
  margin + 12,
  y + 14
);

y += Math.max(
  24,
  lines.length * 5 + 10
);

  });

} else {

  addParagraph(
    "No business insights are currently available."
  );

}

//
// ==================================================
// TOP PERFORMING PRODUCTS
// ==================================================

if (analytics?.top_products?.length) {

  addSectionTitle(
    "Top Performing Products"
  );

  analytics.top_products
    .slice(0,5)
    .forEach((product,index)=>{

      checkPageBreak(18);

      const productName =
        product.product_name ||
        product.name ||
        `Product ${index+1}`;

      const revenue =
        product.revenue ??
        product.total_revenue;

      pdf.setFillColor(
        255,
        255,
        255
      );

      pdf.setDrawColor(
        226,
        232,
        240
      );

      pdf.roundedRect(
        margin,
        y,
        contentWidth,
        16,
        3,
        3,
        "FD"
      );

      pdf.setFillColor(
        79,
        70,
        229
      );

      pdf.circle(
        margin + 7,
        y + 8,
        3,
        "F"
      );

      pdf.setFont(
        "helvetica",
        "bold"
      );

      pdf.setFontSize(9);

      pdf.setTextColor(
        255,
        255,
        255
      );

      pdf.text(
        String(index+1),
        margin + 7,
        y + 9,
        {
          align:"center"
        }
      );

      pdf.setFont(
        "helvetica",
        "bold"
      );

      pdf.setFontSize(11);

      pdf.setTextColor(
        30,
        41,
        59
      );

      pdf.text(
        productName,
        margin + 15,
        y + 7
      );

      pdf.setFont(
        "helvetica",
        "normal"
      );

      pdf.setFontSize(9);

      pdf.setTextColor(
        100,
        116,
        139
      );

      pdf.text(
        revenue
          ? formatMoney(revenue)
          : "-",
        pageWidth - margin - 4,
        y + 7,
        {
          align:"right"
        }
      );

      pdf.text(
        "Revenue Generated",
        pageWidth - margin - 4,
        y + 12,
        {
          align:"right"
        }
      );

      y += 20;

    });

}

//
// ==================================================
// AI EXECUTIVE SUMMARY
// ==================================================

addSectionTitle(
  "AI Executive Summary"
);

checkPageBreak(45);

pdf.setFillColor(
  239,
  246,
  255
);

pdf.setDrawColor(
  191,
  219,
  254
);

pdf.roundedRect(
  margin,
  y,
  contentWidth,
  42,
  4,
  4,
  "FD"
);

pdf.setFont(
  "helvetica",
  "bold"
);

pdf.setFontSize(12);

pdf.setTextColor(
  30,
  64,
  175
);

pdf.text(
  "Executive Overview",
  margin + 8,
  y + 10
);

pdf.setFont(
  "helvetica",
  "normal"
);

pdf.setFontSize(10);

pdf.setTextColor(
  71,
  85,
  105
);

const summaryText =
  ai?.summary ||
  "AI executive analysis is currently unavailable.";

const summaryLines =
  pdf.splitTextToSize(
    summaryText,
    contentWidth - 16
  );

pdf.text(
  summaryLines,
  margin + 8,
  y + 20
);

y += Math.max(
  48,
  summaryLines.length * 5 + 24
);

  // ==================================================
// AI RECOMMENDATIONS
// ==================================================

addSectionTitle("AI Recommendations");

if (ai?.recommendations?.length) {

  ai.recommendations.forEach((recommendation, index) => {

    checkPageBreak(22);

    pdf.setFillColor(240,253,244);
    pdf.setDrawColor(187,247,208);

    pdf.roundedRect(
      margin,
      y,
      contentWidth,
      18,
      4,
      4,
      "FD"
    );

    pdf.setFillColor(
      22,
      163,
      74
    );

    pdf.circle(
      margin + 7,
      y + 8,
      3,
      "F"
    );

    pdf.setFont(
      "helvetica",
      "bold"
    );

    pdf.setFontSize(8);

    pdf.setTextColor(
      255,
      255,
      255
    );

    pdf.text(
      String(index + 1),
      margin + 7,
      y + 9,
      {
        align: "center",
      }
    );

    pdf.setFont(
      "helvetica",
      "normal"
    );

    pdf.setFontSize(10);

    pdf.setTextColor(
      55,
      65,
      81
    );

    const lines =
      pdf.splitTextToSize(
        recommendation,
        contentWidth - 18
      );

    pdf.text(
      lines,
      margin + 14,
      y + 9
    );

    y += Math.max(
      22,
      lines.length * 5 + 8
    );

  });

} else {

  addParagraph(
    "No AI recommendations are currently available."
  );

}

//
// ==================================================
// BUSINESS RISKS
// ==================================================

addSectionTitle(
  "Business Risks"
);

if (ai?.risks?.length) {

  ai.risks.forEach((risk)=>{

    checkPageBreak(22);

    pdf.setFillColor(
      254,
      242,
      242
    );

    pdf.setDrawColor(
      254,
      202,
      202
    );

    pdf.roundedRect(
      margin,
      y,
      contentWidth,
      18,
      4,
      4,
      "FD"
    );

    pdf.setFillColor(
      220,
      38,
      38
    );

    pdf.circle(
      margin + 7,
      y + 8,
      3,
      "F"
    );

    pdf.setFont(
      "helvetica",
      "bold"
    );

    pdf.setFontSize(8);

    pdf.setTextColor(
      255,
      255,
      255
    );

    pdf.text(
      "!",
      margin + 7,
      y + 9,
      {
        align:"center"
      }
    );

    pdf.setFont(
      "helvetica",
      "normal"
    );

    pdf.setFontSize(10);

    pdf.setTextColor(
      71,
      85,
      105
    );

    const lines =
      pdf.splitTextToSize(
        risk,
        contentWidth - 18
      );

    pdf.text(
      lines,
      margin + 14,
      y + 9
    );

    y += Math.max(
      22,
      lines.length * 5 + 8
    );

  });

} else {

  addParagraph(
    "No significant business risks detected."
  );

}

//
// ==================================================
// REPORT SUMMARY
// ==================================================

checkPageBreak(40);

pdf.setFillColor(
  15,
  23,
  42
);

pdf.roundedRect(
  margin,
  y,
  contentWidth,
  32,
  4,
  4,
  "F"
);

pdf.setFont(
  "helvetica",
  "bold"
);

pdf.setFontSize(13);

pdf.setTextColor(
  255,
  255,
  255
);

pdf.text(
  "Report Summary",
  margin + 8,
  y + 10
);

pdf.setFont(
  "helvetica",
  "normal"
);

pdf.setFontSize(10);

pdf.setTextColor(
  226,
  232,
  240
);

pdf.text(
  "This report provides an executive overview of your marketplace performance, benchmark ranking, AI-driven insights, business opportunities, and operational risks based on the latest analytical data available in ShopSense.",
  margin + 8,
  y + 20,
  {
    maxWidth: contentWidth - 16,
  }
);

y += 42;

//
// ==================================================
// REPORT METADATA
// ==================================================

checkPageBreak(25);

pdf.setDrawColor(
  226,
  232,
  240
);

pdf.line(
  margin,
  y,
  pageWidth - margin,
  y
);

y += 8;

pdf.setFont(
  "helvetica",
  "normal"
);

pdf.setFontSize(8);

pdf.setTextColor(
  120,
  120,
  120
);

pdf.text(
  `Vendor: ${vendorName}`,
  margin,
  y
);

pdf.text(
  `Generated: ${generatedDate}`,
  pageWidth / 2,
  y
);

pdf.text(
  "Version 1.0",
  pageWidth - margin,
  y,
  {
    align:"right"
  }
);

//
// ==================================================
// FOOTER
// ==================================================

addFooter();

//
// ==================================================
// SAVE REPORT
// ==================================================

const dateForFile =
  new Date()
    .toISOString()
    .slice(0,10);

pdf.save(
  `ShopSense_Business_Report_${dateForFile}.pdf`
);
};